package view;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Computador;
import model.Sessao;
import model.Status;
import model.StatusSess;
import model.dao.ClienteDAO;
import model.dao.ComputadorDAO;

public class CadastroSessaoJD extends javax.swing.JDialog {

    private Sessao sessao;
    private ClienteDAO clienteDAO;
    private ComputadorDAO computadorDAO;

    public CadastroSessaoJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        clienteDAO = new ClienteDAO();
        computadorDAO = new ComputadorDAO();

        txtHoraInicio.setToolTipText("Formato: HH:mm (Ex: 14:30)");
        txtHoraFim.setToolTipText("Formato: HH:mm (Ex: 16:45)");

        loadClientes();
        loadComputadores();
        loadStatusSess();

        sessao = new Sessao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnoFabricacao1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblValorHora = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtHoraInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHoraFim = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbComputador = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setText("Ano Fabricação");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro da Sessão");

        lblNome.setText("Cliente");

        jLabel2.setText("Computador");

        jLabel3.setText("Hora Inicio");

        lblValorHora.setText("Valor por Hora");

        txtValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorHoraActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Hora Final");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        jLabel4.setText("Obs: Somente insira a hora final ao final da sessão!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                    .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(cmbComputador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblValorHora)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbComputador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (sessao == null) {
            sessao = new Sessao();
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        try {
            sessao.setCliente((Cliente) cmbCliente.getSelectedItem());
            Computador computadorSelecionado = (Computador) cmbComputador.getSelectedItem();
            sessao.setComputador(computadorSelecionado);

            LocalTime horaInicio = LocalTime.parse(txtHoraInicio.getText().trim(), formatter);
            sessao.setHoraInicio(horaInicio);

            if (!txtHoraFim.getText().trim().isEmpty()) {
                LocalTime horaFinal = LocalTime.parse(txtHoraFim.getText().trim(), formatter);
                sessao.setHoraFinal(horaFinal);

                double valorHora = Double.parseDouble(txtValorHora.getText().trim().replace(",", "."));
                sessao.setValorHora(valorHora);

                double valorTotalCalculado = sessao.calcularValorTotal();
                sessao.setValorTotal(valorTotalCalculado);
                sessao.setStatus(StatusSess.INATIVA);

                // libera o pc quando a sessao termina
                computadorSelecionado.setStatus(Status.LIVRE);
                computadorDAO.persist(computadorSelecionado);

            } else {
                sessao.setValorTotal(0.0);
                sessao.setStatus(StatusSess.ATIVA);

                double valorHora = Double.parseDouble(txtValorHora.getText().trim().replace(",", "."));
                sessao.setValorHora(valorHora);

                // ocupa o pc quando a sessao inicia
                computadorSelecionado.setStatus(Status.OCUPADO);
                computadorDAO.persist(computadorSelecionado);
            }

            this.dispose();

        } catch (NumberFormatException e1) {
            sessao = null;
            JOptionPane.showMessageDialog(rootPane, "Erro de formato. Verifique se o Valor por Hora está correto.\nDetalhe: " + e1.getMessage());
        } catch (DateTimeParseException e2) {
            sessao = null;
            JOptionPane.showMessageDialog(rootPane, "Erro de formato. Verifique se as Horas (Início/Fim) estão no formato correto (Ex: 14:30).\nDetalhe: " + e2.getMessage());
        } catch (Exception e3) {
            sessao = null;
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado:\n" + e3.getMessage());
            e3.printStackTrace();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSessaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSessaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSessaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSessaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroSessaoJD dialog = new CadastroSessaoJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cmbCliente;
    private javax.swing.JComboBox<Computador> cmbComputador;
    private javax.swing.JComboBox<StatusSess> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JTextField txtAnoFabricacao1;
    private javax.swing.JTextField txtHoraFim;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables

    private void loadStatusSess() {
        cmbStatus.removeAllItems();
        for (StatusSess obj : StatusSess.values()) {
            cmbStatus.addItem(obj);
        }
    }

    private void loadClientes() {
        cmbCliente.removeAllItems();
        List<Cliente> clientes = clienteDAO.listaClientes();

        if (clientes != null && !clientes.isEmpty()) {
            for (Cliente cliente : clientes) {
                cmbCliente.addItem(cliente);
            }
        } else {
            System.out.println("AVISO: Nenhum cliente encontrado!");
        }
    }

    private void loadComputadores() {
        cmbComputador.removeAllItems();
        List<Computador> computadores = computadorDAO.listaComputadores();

        if (computadores != null && !computadores.isEmpty()) {
            for (Computador comp : computadores) {
                if (comp.getStatus() == Status.LIVRE) {
                    cmbComputador.addItem(comp);
                }
            }
        } else {
            System.out.println("AVISO: Nenhum computador encontrado!");
        }
    }

    public Sessao getSessao() {
        return sessao;
    }

    public void setSessao(Sessao sessao) {
        this.sessao = sessao;

        cmbCliente.setSelectedItem(sessao.getCliente());

        //recarrega os computadores, ate os que já estao na sessão
        loadComputadoresParaEdicao(sessao.getComputador());
        cmbComputador.setSelectedItem(sessao.getComputador());

        if (sessao.getHoraInicio() != null) {
            txtHoraInicio.setText(sessao.getHoraInicio().format(DateTimeFormatter.ofPattern("HH:mm")));
        }

        if (sessao.getHoraFinal() != null) {
            txtHoraFim.setText(sessao.getHoraFinal().format(DateTimeFormatter.ofPattern("HH:mm")));
        }
        cmbStatus.setSelectedItem(sessao.getStatus());
        txtValorHora.setText(String.format("%.2f", sessao.getValorHora()));
    }

    // carregar computadores ao editar
    private void loadComputadoresParaEdicao(Computador computadorAtual) {
        cmbComputador.removeAllItems();
        List<Computador> computadores = computadorDAO.listaComputadores();

        if (computadores != null && !computadores.isEmpty()) {
            for (Computador comp : computadores) {
                // se estiver disponível ou se for o computador atual ele adiciona
                if (comp.getStatus() == Status.LIVRE || comp.getId().equals(computadorAtual.getId())) {
                    cmbComputador.addItem(comp);
                }
            }
        }
    }
}
